name: CI/CD for Stop-Watch-App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name:  Setup Python
        uses: actions/setup-python@v4.7.1
        
      - name: Confirm python 
        run: python --version
        
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Building App
        run: echo 'buliding application'


  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Deploy to Azure Vitual Machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
         sudo apt update
         sudo apt install nginx
          
      
