name: CI/CD for Stop-Watch-App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name:  Setup Python
        uses: actions/setup-python@v4.7.1
        
      - name: Confirm python 
        run: python --version  

        
